name: CI

on:
  push:
    branches: ['main', 'testing']
  pull_request:
    branches: ['main', 'testing']

jobs:
  check:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm lint
      
      - name: Format check
        run: pnpm prettier --check .
        
      - name: Build
        run: pnpm build